
///$tab SUB Meta
Sub Meta (vTable)

let vSubEnd = now();
let vSubTime = Interval('$(vSubStart)' - '$(vSubEnd)');

Metadata:
Load
	'$(vSubStart)'			as Meta_Start
,	'$(vSubEnd)'			as Meta_End
,	'$(vSubTime)'			as Meta_Time
,	'$(vTable)'				as Meta_Table
,	NoOfRows('$(vTable)') 	as Meta_NoOfRows
,	NoOfFields('$(vTable)')	as Meta_NoOfCols
,	'ALL_META'				as ALL_META
AutoGenerate 1;

end sub;

//Set vSubStart Now, in case the user forgets to set it later.
let vSubStart = now();

//---SUB START----//
let vSubStart = now();
//---SUB START----//

Blah:
Load
	[AncestorID]	as	[XX_AncestorID],
	[%Salesperson ID]	as	[XX_%Salesperson ID],
	[Salesperson]	as	[XX_Salesperson],
	[AncestorName]	as	[XX_AncestorName],
	[Sales Person Title]	as	[XX_Sales Person Title],
	[Sales Person First Name]	as	[XX_Sales Person First Name],
	[Sales Person Last Name]	as	[XX_Sales Person Last Name],
	[Heirarchy]	as	[XX_Heirarchy],
	'ALL_BLAH'	as	ALL_BLAH
from [/Users/ben/Copy/Repositories/Qlik-Script-Tools/qvd/TestEmployees.qvd] (qvd)
;

//---SUB END----//
Call Meta ('@0')
//---SUB END----//
