///$tab A

Trace #### TAB A ### ;
A:
Load
	RowNo() as Test1_ID
,	'Category' & Pick(Round(Rand()*4)+1) as Test1_Category
,	Rand()*1000 as Test1_Value
AutoGenerate 1000;

///$tab B

Trace #### TAB B ### ;
B:
Load
	RowNo() as Test2_ID
,	'Category' & Pick(Round(Rand()*4)+1) as Test2_Category
,	Rand()*1000 as Test2_Value
AutoGenerate 1000;

///$tab C

Trace #### TAB C ### ;
C:
Load
	RowNo() as Test3_ID
,	'Category' & Pick(Round(Rand()*4)+1) as Test3_Category
,	Rand()*1000 as Test1_Value
AutoGenerate 1000;
